server:
  port: 8082

spring:
  application:
    name: fraud
  datasource:
    username: 'user'
    password: 'password'
    url: jdbc:mysql://localhost:3308/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
