services:
  sqldb:
    image: mysql:8.0
    restart: always
    container_name: mysql_database
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mySqlDB:/var/lib/mysql
    networks:
      - mySql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: '1'
    networks:
      - mySql
    links:
      - sqldb:db

volumes:
  mySqlDB:

networks:
  mySql:

