services:
  customer:
    image: mysql:8.0
    restart: always
    container_name: customer_database
    environment:
      MYSQL_DATABASE: 'customer'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - customerDB:/var/lib/mysql
    networks:
      - mySql

  fraud:
    image: mysql:8.0
    restart: always
    container_name: fraud_database
    environment:
      MYSQL_DATABASE: 'fraud'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
        - '3308:3306'
    expose:
        - '3306'
    volumes:
        - fraudDB:/var/lib/mysql
    networks:
        - mySql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: '1'
    networks:
      - mySql
    links:
      - customer:db
      - fraud:db

volumes:
  customerDB:
  fraudDB:

networks:
  mySql:

