server:
  port: 8080


spring:
  application:
    name: customer
  datasource:
    username: 'user'
    password: 'password'
    url: jdbc:mysql://localhost:3307/customer
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true

